apiVersion: v1
kind: Service
metadata:
  name: {{ include "securestore.minioName" . }}
  labels:
    {{- include "securestore.labels" . | nindent 4 }}
spec:
  type: {{ .Values.minio.service.type }}
  ports:
    - name: api
      port: {{ .Values.minio.service.apiPort }}
      targetPort: api
      protocol: TCP
      {{- if and (eq .Values.minio.service.type "NodePort") .Values.minio.service.apiNodePort }}
      nodePort: {{ .Values.minio.service.apiNodePort }}
      {{- end }}
    - name: console
      port: {{ .Values.minio.service.consolePort }}
      targetPort: console
      protocol: TCP
      {{- if and (eq .Values.minio.service.type "NodePort") .Values.minio.service.consoleNodePort }}
      nodePort: {{ .Values.minio.service.consoleNodePort }}
      {{- end }}
  selector:
    {{- include "securestore.selectorLabels" . | nindent 4 }}
